version: "3.11"
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - postgres_static_data:/vol/web
    ports:
      - 8000:8000
    image: api:django
    container_name: userapi_container
    command: >
         /bin/sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=userapi
      - DB_USER=postgres
      - DB_PASS=7034
  db:
    image: postgres:latest
    volumes:
      - userapi:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=userapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7034
    container_name: userapi
volumes:
  userapi:
  postgres_static_data:

